---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[awslogs-agent::default]
    attributes:
      awslogs_agent:
        streams:
          'test.log':
            file: '/var/log/test.log'
            log_group_name: 'test'
            datetime_format: '%Y-%m-%d %H:%M:%S'
            log_stream_name: '{instance_id}'
